import React from 'react';
import { View, Text, ScrollView, StyleSheet, SafeAreaView, TouchableOpacity, StatusBar } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Icon from 'react-native-vector-icons/Feather';

const Output = ({ route, navigation }) => {
  const { result = '', model = 'gemini-1.5-flash', prompt = '' } = route.params || {};

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor="#1E3A8A" />
      <LinearGradient colors={['#1E3A8A', '#3B82F6']} style={styles.header}>
        <View style={styles.headerRow}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
            <Icon name="arrow-left" size={22} color="#fff" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Result</Text>
          <View style={{ width: 40 }} />
        </View>
      </LinearGradient>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {!!prompt && (
          <View style={styles.section}>
            <Text style={styles.label}>Your Question</Text>
            <Text style={styles.block}>{prompt}</Text>
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.label}>AI Output</Text>
          <Text style={styles.block}>{result || 'No result.'}</Text>
          <Text style={styles.meta}>Generated by {model}</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  header: { paddingTop: 20, paddingBottom: 16, paddingHorizontal: 16 },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerTitle: { color: '#fff', fontSize: 18, fontWeight: '600' },
  backButton: { padding: 8 },
  content: { padding: 16 },
  section: { marginBottom: 16, backgroundColor: '#fff', borderRadius: 12, padding: 16, elevation: 2 },
  label: { fontSize: 14, color: '#64748B', marginBottom: 8 },
  block: { fontSize: 16, color: '#0F172A', lineHeight: 22 },
  meta: { marginTop: 8, fontSize: 12, color: '#94A3B8' },
});

export default Output;


