import React from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  Dimensions,
  TouchableOpacity,
} from 'react-native';

const { width } = Dimensions.get('window');

/**
 * ConceptGraph Component
 * Displays Vedic-Modern concept mapping in a visual format
 * Patent-worthy innovation: Visual cross-domain knowledge bridge
 */
const ConceptGraph = ({ vedicMapping, onClose }) => {
  if (!vedicMapping) {
    return null;
  }

  const {
    sutraName,
    modernEquivalent,
    mathematicalField,
    confidenceScore,
    applications,
    crossDomainConnections,
  } = vedicMapping;

  // Convert confidence score to percentage
  const confidencePercentage = Math.round((confidenceScore || 0) * 100);

  // Get confidence color
  const getConfidenceColor = (score) => {
    if (score >= 90) return '#4CAF50'; // Green
    if (score >= 70) return '#FF9800'; // Orange
    return '#F44336'; // Red
  };

  return (
    <ScrollView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Knowledge Mapping</Text>
        {onClose && (
          <TouchableOpacity onPress={onClose} style={styles.closeButton}>
            <Text style={styles.closeButtonText}>✕</Text>
          </TouchableOpacity>
        )}
      </View>

      {/* Vedic Concept Card */}
      <View style={[styles.card, styles.vedicCard]}>
        <View style={styles.cardHeader}>
          <Text style={styles.cardLabel}>Ancient Vedic</Text>
        </View>
        <Text style={styles.conceptTitle}>{sutraName}</Text>
        <View style={styles.badge}>
          <Text style={styles.badgeText}>🕉 Vedic Mathematics</Text>
        </View>
      </View>

      {/* Connection Lines */}
      <View style={styles.connectionContainer}>
        <View style={styles.connectionLine} />
        <View style={styles.confidenceBox}>
          <Text style={styles.confidenceLabel}>Mapping Strength</Text>
          <View style={styles.confidenceBar}>
            <View
              style={[
                styles.confidenceBarFill,
                {
                  width: `${confidencePercentage}%`,
                  backgroundColor: getConfidenceColor(confidencePercentage),
                },
              ]}
            />
          </View>
          <Text style={styles.confidenceText}>{confidencePercentage}% Confidence</Text>
        </View>
        <View style={styles.connectionLine} />
      </View>

      {/* Modern Concept Card */}
      <View style={[styles.card, styles.modernCard]}>
        <View style={styles.cardHeader}>
          <Text style={styles.cardLabel}>Modern Science</Text>
        </View>
        <Text style={styles.conceptTitle}>{modernEquivalent}</Text>
        <View style={styles.badge}>
          <Text style={styles.badgeText}>🔬 {mathematicalField}</Text>
        </View>
      </View>

      {/* Cross-Domain Connections */}
      {crossDomainConnections && Object.keys(crossDomainConnections).length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>🌐 Cross-Domain Connections</Text>
          {Object.entries(crossDomainConnections).map(([field, connection], index) => (
            <View key={index} style={styles.connectionItem}>
              <Text style={styles.connectionField}>
                {field.replace(/_/g, ' ').toUpperCase()}
              </Text>
              <Text style={styles.connectionDescription}>{connection}</Text>
            </View>
          ))}
        </View>
      )}

      {/* Real-World Applications */}
      {applications && applications.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>💡 Real-World Applications</Text>
          {applications.map((app, index) => (
            <View key={index} style={styles.applicationItem}>
              <Text style={styles.applicationBullet}>•</Text>
              <Text style={styles.applicationText}>{app}</Text>
            </View>
          ))}
        </View>
      )}

      {/* Info Footer */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>
          ℹ️ This mapping is generated by VedAI's cross-domain inference engine
        </Text>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  closeButton: {
    padding: 8,
  },
  closeButtonText: {
    fontSize: 24,
    color: '#666',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    margin: 16,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  vedicCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#FF6B6B',
  },
  modernCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#4ECDC4',
  },
  cardHeader: {
    marginBottom: 8,
  },
  cardLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  conceptTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F0F0F0',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  badgeText: {
    fontSize: 12,
    color: '#666',
  },
  connectionContainer: {
    alignItems: 'center',
    marginVertical: 8,
  },
  connectionLine: {
    width: 2,
    height: 20,
    backgroundColor: '#DDD',
  },
  confidenceBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    marginVertical: 4,
    width: width - 64,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  confidenceLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 8,
    textAlign: 'center',
  },
  confidenceBar: {
    height: 8,
    backgroundColor: '#E0E0E0',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 6,
  },
  confidenceBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  confidenceText: {
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#333',
  },
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    margin: 16,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 16,
  },
  connectionItem: {
    marginBottom: 16,
  },
  connectionField: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FF6B6B',
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  connectionDescription: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  applicationItem: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  applicationBullet: {
    fontSize: 16,
    color: '#4ECDC4',
    marginRight: 8,
    marginTop: 2,
  },
  applicationText: {
    flex: 1,
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  footer: {
    padding: 16,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: '#999',
    textAlign: 'center',
    fontStyle: 'italic',
  },
});

export default ConceptGraph;
